spring:
  application:
    name: game-of-three

  data:
    mongodb:
      username: got
      password: secret
      host: localhost
      port: 27017
      database: game_of_three
      authentication-database: admin

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: game-of-three-group
      properties:
        spring.json.trusted.packages: "com.jet.infrastructure.kafka.model"

player:
  player-changed-topic-name: player-events


server:
  port: 8088