spring:
  application:
    name: game-of-three

  data:
    mongodb:
      username: got
      password: secret
      host: localhost
      port: 27017
      database: game_of_three
      authentication-database: admin

server:
  port: 8088